services:
  smfnotify:
    image: ghcr.io/homeworkprod/smfnotify:0.4.0
    volumes:
      - ./config.toml:/config.toml:ro
      - ./last_processed_id:/last_processed_id:rw
    restart: unless-stopped
